---
title: "ACC Analysis"
subtitle: "Project Effect Fire Dung Beetle"
author: "David Vanegas-Alarcón"
format:
  #html:
  pdf:
  #docx: 
    theme: Minty
    light: flatly
    fontsize: 9pt
editor: visual
date: "`r Sys.Date()`"
date-format: long
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(summarytools)
library(GGally)
library(CCA)
library(vegan)
library(CCP)
```

```{r message=FALSE, warning=FALSE}
ACCDB <- read.csv("DataACC.csv", header = T, sep = ";")

ID <- ACCDB[1]
```

Data Frame Summary

```{r}
dfSummary(ACCDB, plain.ascii = FALSE, style = "grid", graph.magnif = 0.75, 
          valid.col = FALSE, tmp.img.dir  = "/tmp")
```

```{r message = FALSE, warning = FALSE, echo = FALSE, fig.width=10, fig.height=7}
# Filter data
dungbeetles <- ACCDB[, 4:8]
soil <- ACCDB[, 9:18]
```

# Analysis ACC

Obtenemos los valores de las correlaciones entre variables 

Conocemos las variables de coprofagos a relacionar

```{r}
names(ACCDB[, 4:8])
```

Conocemos las variables de suelo a relacionar

```{r}
names(ACCDB[, 9:18])
```

```{r message = FALSE, warning = FALSE, echo = FALSE, fig.width=10, fig.height=7}
correlo <- matcor(dungbeetles, soil)  
img.matcor(correlo,  type    =   2)
```


Calculamos las correlaciones canónicas.

```{r}
cc1 <- cc(dungbeetles, soil)
cc1$cor
```



Calculamos los vectores canónicos

```{r}
cc1[3:4]
```

```{r}
barplot(cc1$cor, xlab = "Dimensión", ylab = "Correlaciones canónicas", ylim = c(0, 1))
```

```{r message = FALSE, warning = FALSE, echo = FALSE, fig.width=10, fig.height=7}
cc <- cca(dungbeetles, soil) 
plot(cc)
```

```{r message = FALSE, warning = FALSE, echo = FALSE, fig.width=10, fig.height=7}
plt.cc(cc(dungbeetles, soil), var.label = TRUE, ind.names = ACCDB[,1])
```

# Prueba de dimensiones canónicas

```{r}
rho  <-  cc1$cor 

n  <-  dim(ACCDB)[1] 
p  <-  length(dungbeetles) 
q  <-  length(soil) 

p.asym(rho, n, p, q, tstat ="Wilks")
```

