---
title: "Análisis de datos"
subtitle: "Grupos funcionales"
author: "David Vanegas-Alarcón"
format:
  #html:
  pdf:
  #docx: 
    theme: Minty
    light: flatly
    fontsize: 9pt
editor: visual
date: "`r Sys.Date()`"
date-format: long
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2) # Create Elegant Data Visualisations Using the Grammar of Graphics CRAN v3.5.1
library(dplyr) # A Grammar of Data Manipulation CRAN v1.1.4
library(tidyr) # Tidy Messy Data CRAN v1.3.1
library(FD) # Measuring Functional Diversity (FD) from Multiple Traits, and Other Tools for Functional Ecology CRAN v1.0-12.3 returns the frequencies of each class
library(RVAideMemoire) # Testing and Plotting Procedures for Biostatistics [::NA/NA] v0.9-83-7 # Testing and Plotting Procedures for Biostatistics CRAN v0.9-83-7
library(multcomp) # Simultaneous Inference in General Parametric Models CRAN v1.4-25
library(DescTools)
```

```{r echo=FALSE}
# Read data
DomDB <- read.csv("Dom2.csv", sep = ";") # env
DB2 <- read.csv("sp.csv", sep = ";") # env
GFDB2 <- read.csv("GroupFunc.csv", sep = ";") # env
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
DomDB2  <- as.matrix(DomDB[,-1])
row.names(GFDB2) <- colnames(DomDB2)

DomGF <- functcomp(GFDB2, DomDB2, CWM.type = "all")

dataFG <- DomGF[, 20:36]
dataFG$BurningRegime <- factor(DomDB$X, 
                            levels = c("Null", "Low", "High"))
```

Chi-squared test

```{r echo=FALSE}
values <- matrix(c(80.81081, 38.46154, 9.189189,
                    10.00000, 14.02715, 16.87764,
                    9.189189, 47.511312, 53.164557), 
                  nrow = 3, byrow = TRUE)

# Asignar nombres a las filas y columnas
dimnames(values) <- list(FeedStrategy = c("C", "G", "N"), 
                         BurningRegime = c("High", "Low", "Null"))

# Convertir la matriz en una tabla de contingencia
contDB <- as.table(values)

# Perform chi-squared test
print(chisq.test(contDB))

# Post hoc
PostHocTest(contDB, method = "bonferroni")

```
